---
title: "Difflib and My Attempt to Apply It"
author: "Ephraim Henrichsen"
# date: "2023-04-16"
categories: [difflib, UnReferenced Scripture, Custom, Plagiarism]
---

Difflib is a library designed to help users deal with differences in strings - quantifying differences, identifying similarities, etc.

There's a function in it called get_longest_match which is supposed to get the longest match between two strings. So if I give it the strings: "The cat sat on the mat." and "The dog did not sit on the mat." it should find the match " on the mat."

Though there are other matches, that is the match that is the longest and hence the one it should find.

You may have noticed I said it's "supposed to" get the longest match, instead of saying that it does. That's because it didn't work when I tried it.

It works on many strings, but some strings break it for some reason.

--------------------------------

In my attempts to solve the unreferenced scripture problem, I scraped some data from scriptures.byu.edu, scraping some speeches (about 40) given by Wilford Woodruff and using their pre-identified places where he's citing scripture to compare his words with the words in scripture he's referencing, and programmatically looking through his journal entries to find places where he uses similar phrasing. This tactic obviously wouldn't find all of the places he cites scripture, but it should at least work fairly well to find places he refers in his journal to something he later refers to in a discourse of his.

Unfortunately, this tactic did not work. It found zero matches for some reason.

I believe based on my debugging attempts that difflib's get_matching_blocks function does not work as advertised on all strings, though I'd have to trawl through the source code to investigate why and potentially fix it. It was not identifying matches that I could clearly see were there, though I suppose it could also be due to character encoding issues. Or to a bug in my code.

This merits further research, though I should probably carefully check my code to see if it's doing what I think it's doing.