project:
  type: website

website:
  title: "Plagiarism Detection"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com
  site-url: https://myblogexample.io
  description: Data Science blog
format:
  html:
    theme: morph
    css: styles.css



