---
title: "expquart"
output: 
  html_document:
    theme: cerulean
    code_folding: hide

---

```{r}
library(tidyverse)

```

```{r}
wwPapers <- read.csv("C:/Users/LeRoy12358/Documents/School/W23/499 DS - Senior Project/WWPapers/raw data/2022-12-12-pages-export.csv")
scriptures <- read.csv("C:/Users/LeRoy12358/Documents/School/W23/499 DS - Senior Project/WWPapers/raw data/lds-scriptures.csv")
```

```{r}
# scriptures %>% glimpse()

text <- scriptures %>% select(scripture_text) %>% unlist()

text <- str_replace_all(text, "scripture_text\\d*", "")

text

# ?str_extract_all

```

```{r}
wwPapersShort <- wwPapers %>% head(1000) %>% select(Text.Only.Transcript) %>% distinct()
wwPapersShort
```

```{python}
print("Hello Quarto World!!")
```

```{r}
pacman::p_load("rvest")

articles <- c()

articles <- articles %>% append(read_html("https://scriptures.byu.edu/#:t3d092:p573"))
# articles <- articles %>% append(read_html("https://scriptures.byu.edu/#:t3a99c:p573"))

articles
# articles[1]

mypiece <- read_html("https://scriptures.byu.edu/#:t3d092:p573")
```

```{r}
typeof(mypiece)
names(mypiece)
tmp <- mypiece['node']
tmp
mypiece

mypiece %>% html_element("title") %>% html_text()
mypiece %>% html_element("body") %>% html_text()
mypiece %>% html_nodes("head") %>% html_text()

?html_element

html_elements(mypiece)

mypiece %>% html_nodes('div[id="v25n7"]') %>% html_text()
mypiece %>% html_nodes("html") %>% html_text()
mypiece %>% html_nodes("*") %>% html_text()

myString <- mypiece %>% html_element("body") %>% html_text()
myString2 <- mypiece %>% html_nodes("head") %>% html_text()
myString3 <- mypiece %>% html_nodes("*") %>% html_text()



myString
```

```{r}
fileConn<-file("output.txt")
# writeLines(myString, fileConn)
# writeLines(myString2, fileConn)
writeLines(myString3, fileConn)
close(fileConn)
```

```{r}
mypiece %>% 
  html_nodes("*") %>% 
  html_nodes("*") %>% 
  html_attr("class")

mypiece %>% html_nodes(xpath = '//*[@id=/"jContent/"]') %>% html_text()

mypiece %>% html_text()

read_html("https://scriptures.byu.edu/#:t3d092:p573") %>% html_text()


```


```{r}
pacman::p_load(tidyverse)

content <- read_html("https://scriptures.byu.edu/#:t3d092:p573")

content
```

```{r}
# install.packages("RSelenium")
library(RSelenium)




```


